# Generated by Django 3.2.3 on 2021-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='N', max_length=60),
            preserve_default=False,
        ),
    ]
